<a href="https://colab.research.google.com/github/azrapatvi/movie_recommendation_system/blob/main/movie_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Movie Recommender System

types of recommendation systems :

1.   Content Based : this is basically a type of recommendation system that recommends the items based on past data measn based on your past behaviour it recommends the object
2.   Collaborative Based : this is another type of recommender system that recommends you items based on other person who is similar to you measn lets say a and b both gave 5 rating to a movie then they are considierd to be similar to each other and next time when any one watches another movie then that gets recommende to the other person
1.   hybrid :this is the combination of both recommender systems content based and collaborative based and netflix uses this
here basically system checks your past behaviour also people similar to you and Then gives a final smart recommendation

In [ ]:
!unzip tmdb_5000_credits.csv.zip
!unzip tmdb_5000_movies.csv.zip

Archive:  tmdb_5000_credits.csv.zip
replace tmdb_5000_credits.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: tmdb_5000_credits.csv
Archive:  tmdb_5000_movies.csv.zip
replace tmdb_5000_movies.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: tmdb_5000_movies.csv

In [ ]:
import pandas as pd
import  numpy as np

In [ ]:
credits=pd.read_csv('tmdb_5000_credits.csv')
movies=pd.read_csv('tmdb_5000_movies.csv')

In [ ]:
credits.head(2)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [ ]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

##### Dataset description



1.   Budget: money spent to make the movie
2.   genere: Type of movie (Action, Drama, etc.)
1.   homepage: Official website
2.   id: unique movie id


1.   Keywords:important tags realted to movie
2.   original_language : language of movie


1.   original_title : original movie title ex avatar
2.   overview: short summary or description of a movie


1.   popularity: how popular the movie is the more higher the score the more it is popular
2.   production_companies: Companies that made the movie


1.   production_countries: production countries where the movies were produced
2.   release_date : when the movie was realeased

1.   revenue : money eraned
2.   runtime: duration in mins


1.   spoken_languages: language used in the movie
2.   status : whether it is released or not


1.   vote_average: average movie rating
2.   vote_count: number of people who voted

In [ ]:
movies.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [ ]:
movies.shape

(4803, 20)

In [ ]:
movies['id'].nunique()

4803

there are 20 columns and 4803 rows

In [ ]:
movies.merge(credits,on='title')

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [ ]:
movies.merge(credits,on='title').shape

(4809, 23)

In [ ]:
movies=movies.merge(credits,on='title')

In [ ]:
movies.shape

(4809, 23)

In [ ]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

the difference in original title and title is that in original title the name of movie can be in different langugae but in title the name will always be in english

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [ ]:
# columns to keep
# genres,id (with this column we can get movies posters),keywords,title,overview(if two movies summary is similar means movies too similar),cast(because we recommend movies based on actors like we recommend specific actors movie),crew(recommending movies based on crew)

movies=movies[['genres','movie_id','keywords','title','overview','cast','crew']]

movies.head(2)

,genres,movie_id,keywords,title,overview,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [ ]:
movies.isnull().sum()

genres      0
movie_id    0
keywords    0
title       0
overview    3
cast        0
crew        0
dtype: int64

In [ ]:
movies[movies['overview'].isnull()]

,genres,movie_id,keywords,title,overview,cast,crew
2658,"[{""id"": 18, ""name"": ""Drama""}]",370980,"[{""id"": 717, ""name"": ""pope""}, {""id"": 5565, ""na...",Chiamatemi Francesco - Il Papa della gente,NaN,"[{""cast_id"": 5, ""character"": ""Jorge Mario Berg...","[{""credit_id"": ""5660019ac3a36875f100252b"", ""de..."
4145,"[{""id"": 99, ""name"": ""Documentary""}]",459488,"[{""id"": 6027, ""name"": ""music""}, {""id"": 225822,...","To Be Frank, Sinatra at 100",NaN,"[{""cast_id"": 0, ""character"": ""Narrator"", ""cred...","[{""credit_id"": ""592b25e4c3a368783e065a2f"", ""de..."
4437,"[{""id"": 99, ""name"": ""Documentary""}]",292539,[],Food Chains,NaN,[],"[{""credit_id"": ""5470c3b1c3a368085e000abd"", ""de..."

In [ ]:
movies.dropna(inplace=True)

In [ ]:
movies.duplicated().sum()

np.int64(0)

In [ ]:
movies.iloc[0]

genres      [{"id": 28, "name": "Action"}, {"id": 12, "nam...
movie_id                                                19995
keywords    [{"id": 1463, "name": "culture clash"}, {"id":...
title                                                  Avatar
overview    In the 22nd century, a paraplegic Marine is di...
cast        [{"cast_id": 242, "character": "Jake Sully", "...
crew        [{"credit_id": "52fe48009251416c750aca23", "de...
Name: 0, dtype: object

In [ ]:
movies.iloc[0]['genres']

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [ ]:
# literal_eval is a fucntion that can convert the string of list into list not only it will convert to list but can convert to any data type(like list,tuple,dict etc)

# ex:if you str1='[1,2,3]'
# and if you do list(str1) then output will be like this ['[', '1', ',', ' ', '2', ',', ' ', '3', ']']
# but literal_eval will convert it into proper list that is [1,2,3]

from ast import literal_eval

str1='[1,2,3]'
print(type(str1))
print(type(literal_eval(str1)))
print(literal_eval(str1))

<class 'str'>
<class 'list'>
[1, 2, 3]

In [ ]:
# helper function to get name of genres
import ast

def convert(obj):
  l1=[]
  for i in ast.literal_eval(obj): # loops through all the dictionary present in list
    l1.append(i['name'])

  return l1

In [ ]:
convert(movies.iloc[0]['genres'])

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [ ]:
# as now i have creaed a function and wants to apply it on all the rows of df so apply()

movies['genres']=movies['genres'].apply(convert)

movies.head(2)

,genres,movie_id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [ ]:
# now same function will gets applied on other columns too which are not in proper format

movies['keywords']=movies['keywords'].apply(convert)

In [ ]:
movies.head(2)

,genres,movie_id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [ ]:
movies.iloc[0]['keywords']

['culture clash',
 'future',
 'space war',
 'space colony',
 'society',
 'space travel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alien planet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'love affair',
 'anti war',
 'power relations',
 'mind and soul',
 '3d']

In [ ]:
movies['cast']

0       [{"cast_id": 242, "character": "Jake Sully", "...
1       [{"cast_id": 4, "character": "Captain Jack Spa...
2       [{"cast_id": 1, "character": "James Bond", "cr...
3       [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4       [{"cast_id": 5, "character": "John Carter", "c...
                              ...
4804    [{"cast_id": 1, "character": "El Mariachi", "c...
4805    [{"cast_id": 1, "character": "Buzzy", "credit_...
4806    [{"cast_id": 8, "character": "Oliver O\u2019To...
4807    [{"cast_id": 3, "character": "Sam", "credit_id...
4808    [{"cast_id": 3, "character": "Herself", "credi...
Name: cast, Length: 4806, dtype: object

In [ ]:
movies['cast'][0] # get the 1st row of movies['cast]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [ ]:
l2=movies.iloc[0]['cast']
l3=convert(l2)
l3[:3]

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']

In [ ]:
def get_3_items(obj):
  l1=[]
  for i in ast.literal_eval(obj): # loops through all the dictionary present in list
    l1.append(i['name'])

  return l1[:3]

get_3_items(movies.iloc[0]['cast'])

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']

In [ ]:
movies['cast']=movies['cast'].apply(get_3_items)

In [ ]:
def fetch_director(obj):
  l2=[]
  for i in ast.literal_eval(obj):
    if i['job']=='Director':
      l2.append(i['name'])
      break
  return l2

In [ ]:
movies.iloc[0]

genres          [Action, Adventure, Fantasy, Science Fiction]
movie_id                                                19995
keywords    [culture clash, future, space war, space colon...
title                                                  Avatar
overview    In the 22nd century, a paraplegic Marine is di...
cast         [Sam Worthington, Zoe Saldana, Sigourney Weaver]
crew        [{"credit_id": "52fe48009251416c750aca23", "de...
Name: 0, dtype: object

In [ ]:
movies.iloc[0]['crew']

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [ ]:
fetch_director(movies.iloc[1]['crew'])

['Gore Verbinski']

In [ ]:
movies['crew']=movies['crew'].apply(fetch_director)

movies.head(2)

,genres,movie_id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]

In [ ]:
movies['overview']

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: overview, Length: 4806, dtype: object

In [ ]:
movies['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [ ]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

movies.head(2)

,genres,movie_id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,"[culture clash, future, space war, space colon...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]

In [ ]:
movies['genres'].dtype

dtype('O')

In [ ]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [ ]:
movies.head(2)

,genres,movie_id,keywords,title,overview,cast,crew
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]

In [ ]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [ ]:
movies.head(2)

,genres,movie_id,keywords,title,overview,cast,crew,tags
0,"[Action, Adventure, Fantasy, ScienceFiction]",19995,"[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]",285,"[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."

In [ ]:
df=movies[['movie_id','title','tags']]

df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [ ]:
df['tags']=df['tags'].apply(lambda x:" ".join(x))

/tmp/ipykernel_7187/2493417758.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags']=df['tags'].apply(lambda x:" ".join(x))

In [ ]:
df.iloc[0]

movie_id                                                19995
title                                                  Avatar
tags        In the 22nd century, a paraplegic Marine is di...
Name: 0, dtype: object

In [ ]:
df['tags'].iloc[0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [ ]:
df['tags']=df['tags'].str.lower()

df.head(2)

/tmp/ipykernel_7187/1628182927.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags']=df['tags'].str.lower()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."

In [ ]:
df['tags'].iloc[0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [ ]:
df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,a newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,ever since the second grade when he first saw ...

Bag of Words

In [ ]:
from nltk import PorterStemmer

stemmer=PorterStemmer()

In [ ]:
stemmer

In [ ]:
def stemming(text):
  y=[]

  for i in text.split():
    y.append(stemmer.stem(i))

  return " ".join(y)

In [ ]:
df['tags']=df['tags'].apply(stemming)

/tmp/ipykernel_7187/571263050.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags']=df['tags'].apply(stemming)

In [ ]:
df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

cv

CountVectorizer(max_features=5000, stop_words='english')

In [ ]:
cv.fit_transform(df['tags']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
vectors=cv.fit_transform(df['tags']).toarray() # each movie converted into a vector
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
vectors.shape

(4806, 5000)

In [ ]:
features=cv.get_feature_names_out()
features[:20]

array(['000', '007', '10', '100', '11', '12', '13', '14', '15', '16',
       '17', '17th', '18', '18th', '18thcenturi', '19', '1910', '1920',
       '1930', '1940'], dtype=object)

In [ ]:
len(cv.get_feature_names_out())

5000

In [ ]:
# cosine similarity measn cosine distance between two movies this is not like euclidiean distance here the angle is a distnace between towo movies

In [ ]:
# cosine distance of each movie with each other movie
#1 ->high similarity
#0 ->no similarity

from sklearn.metrics.pairwise import cosine_similarity

similarity=cosine_similarity(vectors) # this calculates distance of 1st movie with other 4806 movies then 2nd movie with other 4806 movie and so on

In [ ]:
similarity

array([[1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
        0.        ],
       [0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
        0.02615329],
       [0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
        0.        ],
       ...,
       [0.04499213, 0.02378257, 0.02451452, ..., 1.        , 0.03962144,
        0.04229549],
       [0.        , 0.        , 0.        , ..., 0.03962144, 1.        ,
        0.08714204],
       [0.        , 0.02615329, 0.        , ..., 0.04229549, 0.08714204,
        1.        ]])

In [ ]:
similarity.shape

(4806, 4806)

In [ ]:
similarity[0]

array([1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
       0.        ])

In [ ]:
similarity[1]

array([0.08346223, 1.        , 0.06063391, ..., 0.02378257, 0.        ,
       0.02615329])

In [ ]:
df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4805,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4807,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4808,25975,My Date with Drew,ever sinc the second grade when he first saw h...

In [ ]:
df[df['title']=='Avatar']

   movie_id   title                                               tags
0     19995  Avatar  in the 22nd century, a parapleg marin is dispa...

In [ ]:
df[df['title']=='Spectre'].index # this gives the index of the Spectre movie

Index([2], dtype='int64')

In [ ]:
indx=df[df['title']=='Spectre'].index[0]
dstns=similarity[indx]
dstns

array([0.0860309 , 0.06063391, 1.        , ..., 0.02451452, 0.        ,
       0.        ])

In [ ]:
sorted(list(enumerate(similarity[3])),reverse=True,key=lambda x:x[1]) # this with the help of lambda function now the list will be sorted based on the similarity if we dont give this then it is doing sort based on index position

[(3, np.float64(0.9999999999999997)),
 (65, np.float64(0.42256142372325745)),
 (428, np.float64(0.3247027084163318)),
 (1361, np.float64(0.3202563076101742)),
 (299, np.float64(0.3181582090733562)),
 (119, np.float64(0.3177444546511212)),
 (1360, np.float64(0.30194054243855883)),
 (210, np.float64(0.2970140370712102)),
 (3593, np.float64(0.27311549679956754)),
 (2509, np.float64(0.26148818018424536)),
 (4641, np.float64(0.22645540682891913)),
 (4229, np.float64(0.21969401455243587)),
 (590, np.float64(0.21025856676559)),
 (762, np.float64(0.2067245576486807)),
 (9, np.float64(0.20483662259967564)),
 (1248, np.float64(0.2021892755431259)),
 (3946, np.float64(0.19878450453017366)),
 (2386, np.float64(0.19814848097530424)),
 (1666, np.float64(0.1976664844429603)),
 (3858, np.float64(0.1971041319963609)),
 (3718, np.float64(0.196116135138184)),
 (4069, np.float64(0.196116135138184)),
 (238, np.float64(0.1935524152846909)),
 (1420, np.float64(0.18681617943926832)),
 (3877, np.float64(0.18663625434750084)),
 (1152, np.float64(0.1849000654084097)),
 (1490, np.float64(0.1849000654084097)),
 (2195, np.float64(0.1849000654084097)),
 (3075, np.float64(0.18183351671314585)),
 (4412, np.float64(0.18183351671314585)),
 (761, np.float64(0.17739371879672483)),
 (2276, np.float64(0.17739371879672478)),
 (3838, np.float64(0.17722938923964165)),
 (3861, np.float64(0.1772293892396416)),
 (286, np.float64(0.17720317769039828)),
 (1875, np.float64(0.1754116038614058)),
 (283, np.float64(0.17225077552896434)),
 (1182, np.float64(0.1711841970043651)),
 (2979, np.float64(0.16984155512168936)),
 (3731, np.float64(0.16984155512168933)),
 (3837, np.float64(0.1689815923548436)),
 (1742, np.float64(0.1675306779862365)),
 (1179, np.float64(0.16537964611894457)),
 (4140, np.float64(0.16531163063339513)),
 (1052, np.float64(0.1626903669564168)),
 (884, np.float64(0.1611258466588724)),
 (739, np.float64(0.16012815380508713)),
 (370, np.float64(0.15914876753019166)),
 (2028, np.float64(0.15781069215799975)),
 (3509, np.float64(0.1576833055970887)),
 (3823, np.float64(0.15724272550828775)),
 (1237, np.float64(0.15701857325533192)),
 (2671, np.float64(0.15701857325533192)),
 (3361, np.float64(0.15701857325533192)),
 (212, np.float64(0.1540833878403414)),
 (1646, np.float64(0.15267620413811478)),
 (2338, np.float64(0.15253477177414312)),
 (2545, np.float64(0.15216262173073553)),
 (2010, np.float64(0.15191090506254998)),
 (2390, np.float64(0.15191090506254995)),
 (2923, np.float64(0.15191090506254995)),
 (3970, np.float64(0.15191090506254995)),
 (314, np.float64(0.1513068831672006)),
 (4736, np.float64(0.1513068831672006)),
 (1203, np.float64(0.15025062674119)),
 (606, np.float64(0.148916158209988)),
 (1147, np.float64(0.148916158209988)),
 (1481, np.float64(0.148916158209988)),
 (425, np.float64(0.14867525836251314)),
 (3037, np.float64(0.14864362196288644)),
 (1472, np.float64(0.14824986333222023)),
 (3418, np.float64(0.14824986333222023)),
 (3873, np.float64(0.14824986333222023)),
 (2262, np.float64(0.147180996735913)),
 (4408, np.float64(0.147180996735913)),
 (1494, np.float64(0.147087101353638)),
 (3939, np.float64(0.14617633655117152)),
 (879, np.float64(0.14504754485877897)),
 (1896, np.float64(0.14504754485877894)),
 (4341, np.float64(0.14504754485877894)),
 (3320, np.float64(0.1447071903540765)),
 (1588, np.float64(0.1441153384245784)),
 (3669, np.float64(0.14322297480788657)),
 (3308, np.float64(0.1426954482463482)),
 (976, np.float64(0.1423540710868647)),
 (1722, np.float64(0.1423540710868647)),
 (3022, np.float64(0.1423540710868647)),
 (3261, np.float64(0.1423540710868647)),
 (209, np.float64(0.1416576493949657)),
 (3393, np.float64(0.1416576493949657)),
 (866, np.float64(0.14153462926807445)),
 (1044, np.float64(0.14146557113794814)),
 (1376, np.float64(0.14146557113794814)),
 (3539, np.float64(0.14146557113794814)),
 (2242, np.float64(0.14131671592979872)),
 (139, np.float64(0.14044168141158106)),
 (553, np.float64(0.1401121345794512)),
 (2156, np.float64(0.13977131156292244)),
 (1085, np.float64(0.13867504905630726)),
 (2724, np.float64(0.13867504905630726)),
 (1254, np.float64(0.13849850531947663)),
 (1246, np.float64(0.1381365031419941)),
 (3645, np.float64(0.13655774839978377)),
 (1350, np.float64(0.13631013668492176)),
 (1555, np.float64(0.13617619485048052)),
 (3456, np.float64(0.13617619485048052)),
 (741, np.float64(0.13592873654160803)),
 (3236, np.float64(0.13592873654160803)),
 (408, np.float64(0.1358732440973515)),
 (1088, np.float64(0.1358732440973515)),
 (1558, np.float64(0.1358732440973515)),
 (2063, np.float64(0.1358732440973515)),
 (2306, np.float64(0.1358732440973515)),
 (2917, np.float64(0.1358732440973515)),
 (3334, np.float64(0.1358732440973515)),
 (3299, np.float64(0.13397282541141672)),
 (31, np.float64(0.13323467750529824)),
 (1419, np.float64(0.13323467750529824)),
 (2279, np.float64(0.13323467750529824)),
 (2560, np.float64(0.13323467750529824)),
 (1459, np.float64(0.13266892260349386)),
 (1635, np.float64(0.13266892260349386)),
 (1197, np.float64(0.13209898731686948)),
 (873, np.float64(0.13155870289605434)),
 (1047, np.float64(0.13074409009212268)),
 (1641, np.float64(0.13074409009212268)),
 (1799, np.float64(0.13074409009212268)),
 (4697, np.float64(0.13074409009212268)),
 (2040, np.float64(0.13030163843373951)),
 (205, np.float64(0.12988108336653276)),
 (808, np.float64(0.12988108336653276)),
 (1517, np.float64(0.12988108336653276)),
 (2547, np.float64(0.12988108336653276)),
 (3508, np.float64(0.12988108336653276)),
 (3076, np.float64(0.12941939442218642)),
 (714, np.float64(0.12857571271486287)),
 (2220, np.float64(0.12857571271486287)),
 (615, np.float64(0.12838814775327384)),
 (1421, np.float64(0.12838814775327384)),
 (3114, np.float64(0.12838814775327384)),
 (3597, np.float64(0.12838814775327384)),
 (4251, np.float64(0.12838814775327384)),
 (4652, np.float64(0.12838814775327384)),
 (224, np.float64(0.127381166341267)),
 (3715, np.float64(0.1269166017514316)),
 (351, np.float64(0.1268403984411984)),
 (442, np.float64(0.1268403984411984)),
 (1414, np.float64(0.1268403984411984)),
 (2293, np.float64(0.1265924208854583)),
 (1768, np.float64(0.12639751327042295)),
 (538, np.float64(0.126155140059354)),
 (876, np.float64(0.126155140059354)),
 (1002, np.float64(0.126155140059354)),
 (2555, np.float64(0.126155140059354)),
 (4044, np.float64(0.126155140059354)),
 (3339, np.float64(0.12561485860426555)),
 (4692, np.float64(0.1254363015010636)),
 (737, np.float64(0.12532010295690074)),
 (849, np.float64(0.12532010295690074)),
 (342, np.float64(0.12503908082008883)),
 (1537, np.float64(0.12503908082008883)),
 (777, np.float64(0.12442416956500055)),
 (2282, np.float64(0.12442416956500055)),
 (736, np.float64(0.12403473458920843)),
 (1830, np.float64(0.12403473458920841)),
 (1862, np.float64(0.12403473458920841)),
 (4683, np.float64(0.12403473458920841)),
 (983, np.float64(0.12393235344539924)),
 (1178, np.float64(0.12378237474570462)),
 (659, np.float64(0.12378237474570461)),
 (2062, np.float64(0.12378237474570461)),
 (2634, np.float64(0.12378237474570461)),
 (153, np.float64(0.12357788318574517)),
 (747, np.float64(0.12357788318574517)),
 (1620, np.float64(0.1235415527768502)),
 (2959, np.float64(0.1235415527768502)),
 (3002, np.float64(0.1235415527768502)),
 (694, np.float64(0.12214096331049185)),
 (2400, np.float64(0.12214096331049185)),
 (1247, np.float64(0.12201777521731261)),
 (1400, np.float64(0.12201777521731261)),
 (3295, np.float64(0.12201777521731261)),
 (4452, np.float64(0.12201777521731261)),
 (4781, np.float64(0.12201777521731261)),
 (281, np.float64(0.12104550653376046)),
 (1234, np.float64(0.12070113739631688)),
 (1730, np.float64(0.12070113739631688)),
 (4733, np.float64(0.12070113739631688)),
 (275, np.float64(0.12009611535381534)),
 (974, np.float64(0.12009611535381534)),
 (4330, np.float64(0.12009611535381534)),
 (3550, np.float64(0.12009611535381533)),
 (958, np.float64(0.1194880298498108)),
 (4146, np.float64(0.1194880298498108)),
 (3182, np.float64(0.11948802984981079)),
 (1729, np.float64(0.11894020669001051)),
 (170, np.float64(0.1189402066900105)),
 (1371, np.float64(0.1189402066900105)),
 (894, np.float64(0.11826247919781654)),
 (975, np.float64(0.11826247919781654)),
 (840, np.float64(0.11826247919781653)),
 (3636, np.float64(0.11815292615976111)),
 (3980, np.float64(0.11804804116247142)),
 (1540, np.float64(0.1180480411624714)),
 (4268, np.float64(0.1180480411624714)),
 (3976, np.float64(0.11694106924093721)),
 (2149, np.float64(0.1169410692409372)),
 (116, np.float64(0.11686159857648112)),
 (1322, np.float64(0.11651034560709259)),
 (3259, np.float64(0.11651034560709259)),
 (2961, np.float64(0.11597857493723772)),
 (387, np.float64(0.1156117059711339)),
 (695, np.float64(0.11556254088025608)),
 (1053, np.float64(0.11556254088025608)),
 (1083, np.float64(0.11556254088025608)),
 (1676, np.float64(0.11556254088025608)),
 (2096, np.float64(0.11556254088025608)),
 (3209, np.float64(0.11556254088025608)),
 (72, np.float64(0.1148338503526429)),
 (2732, np.float64(0.1148338503526429)),
 (4667, np.float64(0.11483385035264289)),
 (834, np.float64(0.11440107883060735)),
 (1628, np.float64(0.11440107883060735)),
 (574, np.float64(0.11440107883060732)),
 (4103, np.float64(0.11412279800291009)),
 (497, np.float64(0.11322770341445958)),
 (1434, np.float64(0.11322770341445958)),
 (1783, np.float64(0.11322770341445958)),
 (2437, np.float64(0.11322770341445958)),
 (2880, np.float64(0.11322770341445958)),
 (3854, np.float64(0.11322770341445958)),
 (377, np.float64(0.11322770341445956)),
 (421, np.float64(0.11322770341445956)),
 (892, np.float64(0.11322770341445956)),
 (1001, np.float64(0.11322770341445956)),
 (1039, np.float64(0.11322770341445956)),
 (1515, np.float64(0.11322770341445956)),
 (2640, np.float64(0.11322770341445956)),
 (2670, np.float64(0.11322770341445956)),
 (3494, np.float64(0.11322770341445956)),
 (3688, np.float64(0.11322770341445956)),
 (4137, np.float64(0.11322770341445956)),
 (4171, np.float64(0.11322770341445956)),
 (4178, np.float64(0.11322770341445956)),
 (4211, np.float64(0.11322770341445956)),
 (3201, np.float64(0.11235334512926484)),
 (3543, np.float64(0.11235334512926484)),
 (1036, np.float64(0.11208970766356098)),
 (2481, np.float64(0.11208970766356098)),
 (807, np.float64(0.11168711865749101)),
 (1210, np.float64(0.11168711865749101)),
 (1754, np.float64(0.11168711865749101)),
 (1957, np.float64(0.11168711865749101)),
 (3318, np.float64(0.11168711865749101)),
 (4633, np.float64(0.11168711865749101)),
 (3730, np.float64(0.11118739749916517)),
 (821, np.float64(0.11102889792108188)),
 (2224, np.float64(0.11102889792108188)),
 (3419, np.float64(0.11102889792108188)),
 (3855, np.float64(0.11102889792108188)),
 (4357, np.float64(0.11102889792108188)),
 (4433, np.float64(0.11102889792108188)),
 (4509, np.float64(0.11102889792108188)),
 (3670, np.float64(0.11102889792108186)),
 (3793, np.float64(0.11098534863604861)),
 (758, np.float64(0.1109853486360486)),
 (1450, np.float64(0.11020775375559676)),
 (955, np.float64(0.11020775375559674)),
 (3328, np.float64(0.10991300127873234)),
 (58, np.float64(0.10991300127873233)),
 (776, np.float64(0.10984700727621793)),
 (1433, np.float64(0.10984700727621793)),
 (2776, np.float64(0.10984700727621793)),
 (4259, np.float64(0.10984700727621793)),
 (920, np.float64(0.10895340841010223)),
 (1665, np.float64(0.10895340841010223)),
 (1717, np.float64(0.10895340841010223)),
 (2782, np.float64(0.10895340841010223)),
 (2926, np.float64(0.10895340841010223)),
 (3863, np.float64(0.10895340841010223)),
 (4491, np.float64(0.10895340841010223)),
 (4659, np.float64(0.10895340841010223)),
 (282, np.float64(0.10887114836937548)),
 (731, np.float64(0.10878565864408422)),
 (576, np.float64(0.10878565864408421)),
 (844, np.float64(0.10878565864408421)),
 (1206, np.float64(0.10878565864408421)),
 (1767, np.float64(0.10878565864408421)),
 (2207, np.float64(0.10878565864408421)),
 (4374, np.float64(0.10878565864408421)),
 (4304, np.float64(0.10785837148823897)),
 (632, np.float64(0.10741723110591493)),
 (2900, np.float64(0.10741723110591493)),
 (3035, np.float64(0.10741723110591493)),
 (1084, np.float64(0.10741723110591492)),
 (1447, np.float64(0.10741723110591492)),
 (2462, np.float64(0.10741723110591492)),
 (511, np.float64(0.10699012312772821)),
 (1050, np.float64(0.10699012312772821)),
 (2344, np.float64(0.10699012312772821)),
 (3374, np.float64(0.10699012312772821)),
 (3639, np.float64(0.10699012312772821)),
 (717, np.float64(0.10687334289668037)),
 (1926, np.float64(0.10687334289668037)),
 (1954, np.float64(0.10687334289668037)),
 (189, np.float64(0.10675210253672475)),
 (1076, np.float64(0.10675210253672475)),
 (1617, np.float64(0.10675210253672475)),
 (4147, np.float64(0.10675210253672475)),
 (4163, np.float64(0.10675210253672475)),
 (4557, np.float64(0.10675210253672475)),
 (369, np.float64(0.1060991783534611)),
 (1598, np.float64(0.1060991783534611)),
 (2373, np.float64(0.1060991783534611)),
 (354, np.float64(0.10591481821704041)),
 (2048, np.float64(0.10591481821704041)),
 (356, np.float64(0.105129283382795)),
 (826, np.float64(0.105129283382795)),
 (2037, np.float64(0.105129283382795)),
 (3555, np.float64(0.105129283382795)),
 (160, np.float64(0.10510691307008661)),
 (4532, np.float64(0.1051069130700866)),
 (696, np.float64(0.10498162982203109)),
 (2065, np.float64(0.10498162982203109)),
 (2404, np.float64(0.10482848367219183)),
 (3732, np.float64(0.10455225530359843)),
 (3324, np.float64(0.10407268085375919)),
 (3729, np.float64(0.10407268085375919)),
 (950, np.float64(0.1039048666932262)),
 (993, np.float64(0.1039048666932262)),
 (1775, np.float64(0.1039048666932262)),
 (2132, np.float64(0.1039048666932262)),
 (2775, np.float64(0.1039048666932262)),
 (3175, np.float64(0.1039048666932262)),
 (3241, np.float64(0.1039048666932262)),
 (3301, np.float64(0.1039048666932262)),
 (3411, np.float64(0.1039048666932262)),
 (4645, np.float64(0.1039048666932262)),
 (1011, np.float64(0.10360237735649558)),
 (1911, np.float64(0.10360237735649558)),
 (3671, np.float64(0.10360237735649558)),
 (1025, np.float64(0.10336227882434035)),
 (1077, np.float64(0.10336227882434035)),
 (1488, np.float64(0.10336227882434035)),
 (1627, np.float64(0.10336227882434035)),
 (2497, np.float64(0.10336227882434035)),
 (3262, np.float64(0.10336227882434035)),
 (4579, np.float64(0.10336227882434035)),
 (1986, np.float64(0.10322795481850182)),
 (622, np.float64(0.10318693980271744)),
 (1458, np.float64(0.10318693980271744)),
 (4198, np.float64(0.10318693980271744)),
 (3789, np.float64(0.10256410256410255)),
 (339, np.float64(0.10241831129983783)),
 (1363, np.float64(0.10241831129983782)),
 (1948, np.float64(0.10241831129983782)),
 (2052, np.float64(0.10241831129983782)),
 (2348, np.float64(0.10241831129983782)),
 (3843, np.float64(0.10241831129983782)),
 (355, np.float64(0.10191289532899897)),
 (2430, np.float64(0.10191289532899897)),
 (981, np.float64(0.1016814793477605)),
 (1436, np.float64(0.1016814793477605)),
 (2231, np.float64(0.1016814793477605)),
 (2584, np.float64(0.1016814793477605)),
 (2611, np.float64(0.1016814793477605)),
 (3764, np.float64(0.1016814793477605)),
 (4702, np.float64(0.1016814793477605)),
 (654, np.float64(0.101481253070083)),
 (980, np.float64(0.101481253070083)),
 (629, np.float64(0.10127393670836667)),
 (1701, np.float64(0.10127393670836667)),
 (4435, np.float64(0.10127393670836667)),
 (647, np.float64(0.10127393670836665)),
 (962, np.float64(0.10127393670836665)),
 (1195, np.float64(0.10127393670836665)),
 (1995, np.float64(0.10127393670836665)),
 (2271, np.float64(0.10127393670836665)),
 (2295, np.float64(0.10127393670836665)),
 (2586, np.float64(0.10127393670836665)),
 (3064, np.float64(0.10127393670836665)),
 (3625, np.float64(0.10127393670836665)),
 (3644, np.float64(0.10127393670836665)),
 (4463, np.float64(0.10127393670836665)),
 (4160, np.float64(0.10127393670836662)),
 (1451, np.float64(0.10065952899503389)),
 (3698, np.float64(0.10065952899503389)),
 (1059, np.float64(0.10016708449412667)),
 (1629, np.float64(0.10016708449412667)),
 (529, np.float64(0.10016708449412666)),
 (1486, np.float64(0.10008009612817945)),
 (2257, np.float64(0.10008009612817945)),
 (4475, np.float64(0.10008009612817945)),
 (4569, np.float64(0.10008009612817945)),
 (1637, np.float64(0.10003126465607105)),
 (2599, np.float64(0.0998574482525463)),
 (41, np.float64(0.09909574797525764)),
 (724, np.float64(0.09909574797525762)),
 (1221, np.float64(0.09909574797525762)),
 (2651, np.float64(0.09909574797525762)),
 (3799, np.float64(0.09909574797525762)),
 (38, np.float64(0.09907424048765212)),
 (252, np.float64(0.09907424048765211)),
 (1634, np.float64(0.09907424048765211)),
 (3940, np.float64(0.09907424048765211)),
 (613, np.float64(0.09883324222148016)),
 (1238, np.float64(0.09883324222148016)),
 (1802, np.float64(0.09883324222148016)),
 (2334, np.float64(0.09883324222148016)),
 (2950, np.float64(0.09883324222148016)),
 (2960, np.float64(0.09883324222148016)),
 (3435, np.float64(0.09883324222148016)),
 (3489, np.float64(0.09883324222148016)),
 (4256, np.float64(0.09883324222148016)),
 (4783, np.float64(0.09883324222148016)),
 (303, np.float64(0.09855206599818045)),
 (672, np.float64(0.09855206599818045)),
 (1663, np.float64(0.09855206599818045)),
 (1855, np.float64(0.09855206599818045)),
 (2401, np.float64(0.09855206599818045)),
 (2793, np.float64(0.09855206599818045)),
 (3547, np.float64(0.09855206599818045)),
 (3821, np.float64(0.09855206599818045)),
 (4775, np.float64(0.09855206599818045)),
 (1270, np.float64(0.09805806756909201)),
 (1274, np.float64(0.09805806756909201)),
 (1453, np.float64(0.09805806756909201)),
 (2003, np.float64(0.09805806756909201)),
 (3227, np.float64(0.09805806756909201)),
 (4187, np.float64(0.09805806756909201)),
 (444, np.float64(0.098058067569092)),
 (767, np.float64(0.098058067569092)),
 (1466, np.float64(0.098058067569092)),
 (2588, np.float64(0.098058067569092)),
 (4795, np.float64(0.098058067569092)),
 (2444, np.float64(0.09767725810110085)),
 (307, np.float64(0.09760722349103468)),
 (1134, np.float64(0.09760722349103468)),
 (2418, np.float64(0.09756156783416058)),
 (4075, np.float64(0.09756156783416058)),
 (147, np.float64(0.09709195467257715)),
 (405, np.float64(0.09709195467257715)),
 (468, np.float64(0.09709195467257715)),
 (2202, np.float64(0.09709195467257715)),
 (2589, np.float64(0.09709195467257715)),
 (2919, np.float64(0.09709195467257715)),
 (3528, np.float64(0.09709195467257715)),
 (3541, np.float64(0.09709195467257715)),
 (782, np.float64(0.09705231721239392)),
 (611, np.float64(0.09705231721239391)),
 (1144, np.float64(0.09705231721239391)),
 (1265, np.float64(0.09705231721239391)),
 (469, np.float64(0.09683075928319534)),
 (1894, np.float64(0.09683075928319534)),
 (3906, np.float64(0.09683075928319534)),
 (56, np.float64(0.0965609099170535)),
 (1677, np.float64(0.0965609099170535)),
 (2170, np.float64(0.0965609099170535)),
 (3306, np.float64(0.0965609099170535)),
 (3350, np.float64(0.0965609099170535)),
 (3642, np.float64(0.0965609099170535)),
 (2205, np.float64(0.09607689228305227)),
 (4399, np.float64(0.09607689228305227)),
 (2239, np.float64(0.09607689228305226)),
 (449, np.float64(0.09569487529386908)),
 (1010, np.float64(0.09569487529386908)),
 (1745, np.float64(0.09569487529386908)),
 (1807, np.float64(0.09569487529386908)),
 (1846, np.float64(0.09569487529386908)),
 (2171, np.float64(0.09569487529386908)),
 (2380, np.float64(0.09569487529386908)),
 (2414, np.float64(0.09569487529386908)),
 (2442, np.float64(0.09569487529386908)),
 (2658, np.float64(0.09569487529386908)),
 (2763, np.float64(0.09569487529386908)),
 (3345, np.float64(0.09569487529386908)),
 (285, np.float64(0.09541709567944523)),
 (1655, np.float64(0.09541709567944523)),
 (1125, np.float64(0.09513029883089881)),
 (3042, np.float64(0.09513029883089881)),
 (3646, np.float64(0.09513029883089881)),
 (1231, np.float64(0.0951302988308988)),

In [ ]:
df[df['title']=='Avatar']['movie_id'] # with this i can speciifically get movie_id

0    19995
Name: movie_id, dtype: int64

In [ ]:
def recommend(movie):
  movie_index=df[df['title']==movie].index[0]
  distances=similarity[movie_index]

  sorted_movie_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

  for i in sorted_movie_list:
    print(df.iloc[i[0]]['title'])
    #print(i[0]) # gives index of top 5 similar movies
    print()

In [ ]:
recommend('Avatar')

Aliens vs Predator: Requiem

Aliens

Falcon Rising

Independence Day

Titan A.E.

In [ ]:
df.iloc[1214]

movie_id                                                  440
title                             Aliens vs Predator: Requiem
tags        a sequel to 2004' alien vs. predator, the icon...
Name: 1214, dtype: object

In [ ]:
df.iloc[1214]['title']

'Aliens vs Predator: Requiem'

In [ ]:
movie_title=input("enter movie title:")
print("\nRecommended Movies:")
recommend(movie_title)

enter movie title:Aliens vs Predator: Requiem

Recommended Movies:
Slither

Independence Daysaster

AVP: Alien vs. Predator

Aliens in the Attic

Meet Dave